version: "3.8"

services:
  app:
    build: docker/app
    init: true
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./:/app

  nginx:
    image: nginx
    restart: unless-stopped
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./dist:/usr/share/nginx/html:ro
